package com.mycompany.ugallery_proyecto2;
import Estructura.ListaDobleLoteFoto;
import static com.mycompany.ugallery_proyecto2.LoginJFrame.usuarioTXT;
import java.awt.Image;
import java.io.File;
import java.util.*;
import java.util.logging.*;
import javax.swing.*;
import javax.swing.filechooser.*;
import org.apache.commons.io.FilenameUtils;

/**
 *
 * @author manuel
 */
public class BibliotecaJFrame extends javax.swing.JFrame {
    public String NombreUsuario;
    DefaultListModel modeloCategoria = new DefaultListModel();
    ImageIcon iconoImagen;


    public BibliotecaJFrame() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        setTitle("BIBLIOTECA");
        listaCategoriaLT.setModel(modeloCategoria);
        
        NombreUsuario=usuarioTXT.getText();
        Usuario usuarioActual1 = (Usuario) AppState.listaUsuario.find(NombreUsuario);
        DefaultListModel<String> modelo1 = new DefaultListModel<String>();
        
        ArrayList<Categoria> Categorias = usuarioActual1.getListaCategoria();
        for (Categoria categoria : Categorias) {
            modelo1.addElement(categoria.getNombreCategoria());
        }
        listaCategoriaLT.setModel(modelo1); 

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaCategoriaLT = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nombreCategoriaTXT = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        fotoLBL = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        nombreUsuarioTXT = new javax.swing.JTextField();
        nombreFotoTXT = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        rutaTXT = new javax.swing.JTextField();
        jButton8 = new javax.swing.JButton();

        jScrollPane2.setViewportView(jEditorPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(32, 36, 48));

        jButton1.setBackground(new java.awt.Color(117, 232, 250));
        jButton1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("REGRESAR ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        listaCategoriaLT.setBackground(new java.awt.Color(255, 255, 255));
        listaCategoriaLT.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        listaCategoriaLT.setForeground(new java.awt.Color(0, 0, 0));
        listaCategoriaLT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaCategoriaLTMouseClicked(evt);
            }
        });
        listaCategoriaLT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                listaCategoriaLTKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(listaCategoriaLT);

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CATEGORÍA");

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("BIBLIOTECA ");
        jLabel2.setToolTipText("");

        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nombre Categoría:");

        nombreCategoriaTXT.setBackground(new java.awt.Color(255, 255, 255));
        nombreCategoriaTXT.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        nombreCategoriaTXT.setForeground(new java.awt.Color(0, 0, 0));

        jButton2.setBackground(new java.awt.Color(110, 77, 252));
        jButton2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("AGREGAR CATEGORÍA");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(254, 65, 87));
        jButton3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("ELIMINAR CATEGORÍA");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(153, 153, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fotoLBL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fotoLBL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jButton4.setBackground(new java.awt.Color(255, 217, 79));
        jButton4.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 10)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 0, 0));
        jButton4.setText("<");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(255, 217, 79));
        jButton5.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 10)); // NOI18N
        jButton5.setForeground(new java.awt.Color(0, 0, 0));
        jButton5.setText(">");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nombre Usuario:");

        nombreUsuarioTXT.setEditable(false);
        nombreUsuarioTXT.setBackground(new java.awt.Color(255, 255, 255));
        nombreUsuarioTXT.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        nombreUsuarioTXT.setForeground(new java.awt.Color(0, 0, 0));
        nombreUsuarioTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreUsuarioTXTActionPerformed(evt);
            }
        });

        nombreFotoTXT.setEditable(false);
        nombreFotoTXT.setBackground(new java.awt.Color(255, 255, 255));
        nombreFotoTXT.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        nombreFotoTXT.setForeground(new java.awt.Color(0, 0, 0));

        jButton6.setBackground(new java.awt.Color(254, 65, 87));
        jButton6.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("ELIMINAR IMAGEN");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(117, 232, 250));
        jButton7.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jButton7.setForeground(new java.awt.Color(0, 0, 0));
        jButton7.setText("SELECCIONAR IMAGEN");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        rutaTXT.setEditable(false);
        rutaTXT.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N

        jButton8.setBackground(new java.awt.Color(110, 77, 252));
        jButton8.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("AGREGAR IMAGEN");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nombreCategoriaTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(25, 25, 25)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(1, 1, 1)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(rutaTXT)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(86, 86, 86)
                                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nombreFotoTXT)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nombreUsuarioTXT)))
                        .addGap(1, 1, 1)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(nombreUsuarioTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 44, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton6)
                            .addComponent(jButton8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(332, 332, 332)
                                        .addComponent(jLabel3)
                                        .addGap(18, 18, 18)
                                        .addComponent(nombreCategoriaTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton2))
                                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton3)
                                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nombreFotoTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(rutaTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(25, 25, 25))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        LoginJFrame Menu = new LoginJFrame();
        Menu.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Usuario usuarioActual = (Usuario) AppState.listaUsuario.find(NombreUsuario);
        String nombreCategoria=nombreCategoriaTXT.getText();
        if(nombreCategoriaTXT.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Campo Vacío. Debe ingresar el nombre de la categoría.", "Ugallery", JOptionPane.ERROR_MESSAGE);
        }else{
            boolean existe=false;
            for (Categoria categoria : usuarioActual.getListaCategoria()) {
                if(categoria.getNombreCategoria().equals(nombreCategoriaTXT.getText())) {
                    existe = true;
                    break;
                }
            }
            if(existe){
                JOptionPane.showMessageDialog(null, "Esta Categoría Ya Existe.", "Ugallery", JOptionPane.WARNING_MESSAGE);
            }else{
                Categoria nuevaCategoria = new Categoria();
                nuevaCategoria.setNombreCategoria(nombreCategoria);
                usuarioActual.agregarCategoria(nuevaCategoria);
                DefaultListModel<String> modelo2 = (DefaultListModel<String>)listaCategoriaLT.getModel();
                modelo2.addElement(nuevaCategoria.getNombreCategoria());
                listaCategoriaLT.setModel(modelo2);
                JOptionPane.showMessageDialog(null, "Categoría Agregada Correctamente.", "Ugallery", JOptionPane.INFORMATION_MESSAGE);
                
                usuarioActual.ImprimirCategorias();
                nombreCategoriaTXT.setText(null);
                nombreFotoTXT.setText(null);
                fotoLBL.setIcon(null);
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Usuario usuarioActual = (Usuario) AppState.listaUsuario.find(NombreUsuario);
        if(nombreCategoriaTXT.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Campo Vacío. Debe ingresar el nombre de la categoría.", "Ugallery", JOptionPane.ERROR_MESSAGE);
        }else if(nombreCategoriaTXT.getText().equalsIgnoreCase("General")){
             JOptionPane.showMessageDialog(null, "No es posible eliminar la categoría “General”.", "Ugallery", JOptionPane.ERROR_MESSAGE);
        }else{
            boolean existe=false;
            for (Categoria categoria : usuarioActual.getListaCategoria()) {
                if (categoria.getNombreCategoria().equals(nombreCategoriaTXT.getText())) {
                    existe=true;
                    usuarioActual.getListaCategoria().remove(categoria);
                    JOptionPane.showMessageDialog(null, "Categoría Eliminada Correctamente", "Ugallery", JOptionPane.INFORMATION_MESSAGE);
                    
                    usuarioActual.ImprimirCategorias();
                    nombreCategoriaTXT.setText(null);
                    nombreFotoTXT.setText(null);
                    fotoLBL.setIcon(null);
                    break;
                }
            }
            if(!existe){
                JOptionPane.showMessageDialog(null, "Esta Categoría No Existe.", "Ugallery", JOptionPane.ERROR_MESSAGE);
            }else{
                DefaultListModel<String> modelo3 = new DefaultListModel<>();
                for (Categoria categoria : usuarioActual.getListaCategoria()) {
                    modelo3.addElement(categoria.getNombreCategoria());
                }
                listaCategoriaLT.setModel(modelo3);
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        Usuario usuarioActual = (Usuario) AppState.listaUsuario.find(NombreUsuario); 
        Categoria categoria = (Categoria)usuarioActual.listaCategoria.get(listaCategoriaLT.getSelectedIndex());
        
        if(nombreFotoTXT.getText().isEmpty()){
             JOptionPane.showMessageDialog(null, "Selecciona una categoría para cambiar de imagen.", "Ugallery", JOptionPane.ERROR_MESSAGE);
        }else{
            categoria.AnteriorImagen(nombreFotoTXT, fotoLBL);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        Usuario usuarioActual = (Usuario) AppState.listaUsuario.find(NombreUsuario); 
        Categoria categoria = (Categoria)usuarioActual.listaCategoria.get(listaCategoriaLT.getSelectedIndex());
       if(nombreFotoTXT.getText().isEmpty()){
           JOptionPane.showMessageDialog(null, "Selecciona una categoría para cambiar de imagen.", "Ugallery", JOptionPane.ERROR_MESSAGE);
       }else{
           categoria.SiguienteImagen(nombreFotoTXT, fotoLBL);
       }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        if(nombreFotoTXT.getText().isEmpty()){
             JOptionPane.showMessageDialog(null, "Selecciona una categoría para eliminar la imagen.", "Ugallery", JOptionPane.ERROR_MESSAGE);
        }else{
            Usuario usuarioActual = (Usuario) AppState.listaUsuario.find(NombreUsuario); 
            Categoria categoria = (Categoria)usuarioActual.listaCategoria.get(listaCategoriaLT.getSelectedIndex());
            categoria.getListaImagen().delete(nombreFotoTXT.getText());
            JOptionPane.showMessageDialog(null, "Imagen Eliminada Correctamente", "Ugallery", JOptionPane.INFORMATION_MESSAGE);
            categoria.ImprimirImagenes();
            nombreFotoTXT.setText(null);
            fotoLBL.setIcon(null);   
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        JFileChooser jf = new JFileChooser();
        FileFilter filtro1 = new FileNameExtensionFilter("Archivos JPG", "jpg");
        FileFilter filtro2 = new FileNameExtensionFilter("Archivos BMP", "bmp"); 
        jf.setFileFilter(filtro2);
        jf.setFileFilter(filtro1);
        jf.showOpenDialog(this);
        File archivo=jf.getSelectedFile();
        if (archivo!=null){
            rutaTXT.setText(archivo.getAbsolutePath());
            Image foto = getToolkit().getImage(rutaTXT.getText());
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        Usuario UsuarioActual = (Usuario)AppState.listaUsuario.find(NombreUsuario);
        if(rutaTXT.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Seleccionar Una Imagen", "Ugallery", JOptionPane.ERROR_MESSAGE);
        }else if(listaCategoriaLT.getSelectedIndex()==-1){
            JOptionPane.showMessageDialog(null, "Seleccionar Una Categoría De La Imagen", "Ugallery", JOptionPane.ERROR_MESSAGE);
        }else{ 
            File archivo = new File(rutaTXT.getText());
            String fileName=archivo.getName();
                
            String nombre = FilenameUtils.getBaseName(fileName);
            ImageIcon imagen = new ImageIcon(rutaTXT.getText());
            LoteFoto nuevaImagen = new LoteFoto();
            nuevaImagen.setImagenIcon(imagen);
            nuevaImagen.setNombre(nombre);
            nuevaImagen.setRuta(rutaTXT.getText());
            
            Categoria categoria = (Categoria)UsuarioActual.getListaCategoria().get(listaCategoriaLT.getSelectedIndex());
            categoria.agregarImagen(nuevaImagen);
            
            JOptionPane.showMessageDialog(null, "Imagen agregada correctamente a la categoría: "+listaCategoriaLT.getSelectedValue(), "Ugallery", JOptionPane.INFORMATION_MESSAGE); 
            categoria.ImprimirImagenes();
            System.out.println("----------------------------------------------");

            rutaTXT.setText(null);
            nombreFotoTXT.setText(null);
            fotoLBL.setIcon(null);     
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void listaCategoriaLTKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_listaCategoriaLTKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_listaCategoriaLTKeyPressed

    private void nombreUsuarioTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreUsuarioTXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreUsuarioTXTActionPerformed

    private void listaCategoriaLTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaCategoriaLTMouseClicked
        // TODO add your handling code here:
        Usuario usuarioActual = (Usuario) AppState.listaUsuario.find(NombreUsuario); 
        Categoria categoria = (Categoria)usuarioActual.listaCategoria.get(listaCategoriaLT.getSelectedIndex());
        String NombreImagen;
        if(categoria!=null) {
            ListaDobleLoteFoto listaImagenes = categoria.getListaImagen();
            if (listaImagenes.get(0)!=null) {
                LoteFoto iconImagen = (LoteFoto) listaImagenes.get(0);
                NombreImagen =iconImagen.Nombre;
                iconoImagen= iconImagen.getImagenIcon();
                Image Imagen = iconoImagen.getImage();
                Imagen = Imagen.getScaledInstance(fotoLBL.getWidth(), fotoLBL.getHeight(), Image.SCALE_DEFAULT);
                fotoLBL.setIcon(new ImageIcon(Imagen));
                nombreFotoTXT.setText(NombreImagen);
            }else{
                nombreFotoTXT.setText(null);
                fotoLBL.setIcon(null); 
            }
        } 
    }//GEN-LAST:event_listaCategoriaLTMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BibliotecaJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BibliotecaJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BibliotecaJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BibliotecaJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(BibliotecaJFrame.class.getName()).log(Level.SEVERE, null, ex);
                } catch (InstantiationException ex) {
                    Logger.getLogger(BibliotecaJFrame.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IllegalAccessException ex) {
                    Logger.getLogger(BibliotecaJFrame.class.getName()).log(Level.SEVERE, null, ex);
                } catch (UnsupportedLookAndFeelException ex) {
                    Logger.getLogger(BibliotecaJFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
                new BibliotecaJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fotoLBL;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> listaCategoriaLT;
    private javax.swing.JTextField nombreCategoriaTXT;
    public static javax.swing.JTextField nombreFotoTXT;
    public static javax.swing.JTextField nombreUsuarioTXT;
    private javax.swing.JTextField rutaTXT;
    // End of variables declaration//GEN-END:variables
}
